### ISSUE TITLE
Alerta de seguridad de github

### ISSUE THREAD

**Issue by usbceic** [usbceic/ceic-site#15]
Recibí una notificación de github indicando que las versiones de algunos paquetes de pip tienen vulnerabilidades. En específico necesito que alguien cambie esto editando `requirements.txt`. Los paquetes que son vulnerables junto con la versión del mismo a la que se desea actualizar son los siguientes:
* `django>=2.1.2`

**Comment by aitorres** [comment]
Hola @german1608, hablé con @lapy0110, yo me encargo de esto.
